#!/usr/bin/env bash

REPO_ROOT_DIR=$(dirname $(dirname "$(readlink -f "$0")"))
source $REPO_ROOT_DIR/lib/functions

ORCHESTRATION=${1?You must supply an orchestration name}

exec_in_container salt-master "salt-run state.orchestrate $ORCHESTRATION"
